# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date', '-pk'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
