# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190520_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, help_text='Image url', null=True),
        ),
    ]
