# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
